artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/rushin236/Datasets/blob/main/Interview_Intelligence_Prediction/data_ingestion.zip
  data_dir: ["train", "test", "submission"]
